services:
  rpi1:
    image: tianon/raspbian:bullseye
    platform: linux/arm/v6
    container_name: rpi_b_1_2
    tty: true
    stdin_open: true
    command: bash
    volumes:
      - ./data:/data
  rpi3:
    image: balenalib/rpi-raspbian:latest
    platform: linux/arm/v7
    container_name: rpi_b_3
    tty: true
    ports:
      - "5050:5000"
    stdin_open: true
    command: bash
    volumes:
      - ./data:/data
